name: build-ui-application
run-name: ${{ github.actor }} is running GitHub Actions
on: [push]
jobs:
  build-angular-ui-application:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/HappyFamilyUI
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: '20'
      - run: npm install

      - name: Build
        run: npm run build
      
      - name: Package artifacts
        run: zip happy-family-app.zip ./* -r
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: happy-family-app
          path: happy-family-app.zip