name: 'Build Happy Family Application'
run-name: Build Happy Family Application is run by ${{ github.actor }}
on: 
  push:
    branches:
      - main
      - develop
      - feature/*

jobs:
  build-happy-family-app:
    name: 'Build and Upload Artifacts'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Adjust Node.js version as per your requirement

      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend/HappyFamilyUI

      - name: Build Angular Application
        run: npm run build
        working-directory: ./frontend/HappyFamilyUI

      - name: Package Artifacts
        run: zip -r happy-family-ui.zip ./dist/happy-family-ui/*
        working-directory: ./frontend/HappyFamilyUI

      - name: Upload Artifact for Deployment
        uses: actions/upload-artifact@v2
        with:
          name: happy-family-ui
          path: ./frontend/HappyFamilyUI/happy-family-ui.zip
  
  
  deploy-happy-family-app:
    name: 'Deploy on Github Pages'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: happy-family-ui
          path: ./artifact

      - name: Extract Artifact
        run: |
          unzip -q ./artifact/happy-family-ui*.zip -d ./deploy

      # - name: Deploy to GitHub Pages
      #   uses: JamesIves/github-pages-deploy-action@4.2.0
      #   with:
      #     branch: gh-pages  # Branch to deploy to (e.g., gh-pages)
      #     folder: ./deploy  # Folder containing the static site files