name: build-happy-family-application
run-name: ${{ github.actor }} is running GitHub Actions
on: 
  push:
    branches:
      - main
      - develop
      - feature/*

jobs:
  build-angular-ui-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend/HappyFamilyUI

      - name: Build Angular Application
        run: npm run build
        working-directory: ./frontend/HappyFamilyUI

      - name: Get Application Version
        id: version
        run: echo "version=$(node -p 'require(\"./frontend/HappyFamilyUI/package.json\").version')" >> $GITHUB_STATE

      - name: Package Artifacts
        run: |
          source $GITHUB_STATE
          zip -r happy-family-ui@${version}.zip ./frontend/HappyFamilyUI/dist/happy-family-ui/*
        env:
          GITHUB_STATE: ${{ toJson(steps.version.outputs) }}

      - name: Upload Artifact for Deployment
        uses: actions/upload-artifact@v2
        with:
          name: happy-family-ui
          path: ./frontend/HappyFamilyUI/happy-family-ui@v*.zip